import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.trainerize.com/login.aspx")
    page.get_by_role("link", name="sign in").click()
    page.get_by_role("textbox", name="Enter your email Your").click()
    page.get_by_role("textbox", name="Enter your email Your").fill("shannonbirch@cocospersonaltraining.com")
    page.get_by_role("textbox", name="Enter your email Your").press("Enter")
    page.get_by_test_id("email-input").click()
    page.get_by_test_id("email-input").fill("shannonbirch@cocospersonaltraining.com")
    page.get_by_test_id("password-input").click()
    page.get_by_test_id("password-input").fill("cyywp7nyk2")
    page.get_by_test_id("password-input").press("Enter")
    page.get_by_test_id("signIn-button").click()
    page.get_by_test_id("leftNavMenu-item-clients").click()
    page.get_by_test_id("clientGrid-toolbar-addClient").click()
    page.get_by_test_id("addClientDialog-emailInput").fill("shannonbirch@live.com")
    page.get_by_test_id("addClientDialog-firstNameInput").click()
    page.get_by_test_id("addClientDialog-firstNameInput").fill("Shannon")
    page.get_by_test_id("addClientDialog-lastNameInput").click()
    page.get_by_test_id("addClientDialog-lastNameInput").fill("Birch")
    page.get_by_test_id("rolePicker").get_by_text("Full Access 2-way messaging").click()
    page.get_by_role("option", name="Full Access 1-way messaging").click()
    page.get_by_test_id("dialog-defaultFooter-confirm-button").click()
    with page.expect_popup() as page1_info:
        page.get_by_role("button", name="OPEN CLIENT ACCOUNT").click()
    page1 = page1_info.value
    page1.get_by_test_id("leftNavMenu-item-mealPlan").click()
    page1.locator("div").filter(has_text=re.compile(r"^Attach a meal plan PDFSelect a PDF to upload it\.$")).nth(1).click()
    page1.get_by_test_id("nullScreen-upload-button").click()
    page1.get_by_test_id("nullScreen-upload-button").set_input_files("Shannon_Birch_meal_plan_20250508_173956.pdf")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").click()
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").fill("Shannon_Birch_meal_plan_2050508_173956")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").press("ArrowRight")
    page1.get_by_role("textbox", name="Meal plan name, like Balanced").fill("Shannon_Birch_meal_plan")
    page1.get_by_test_id("dialog-defaultFooter-confirm-button").click()
    page1.get_by_test_id("leftNavMenu-item-trainingProgram").click()
    page1.get_by_text("Start building out Shannon's").click()
    page1.get_by_test_id("editTrainingPhase-nameInput").fill("Shannons Program")
    page1.get_by_role("textbox").nth(1).click()
    page1.get_by_text("12", exact=True).click()
    page1.get_by_role("button", name="Increase Value").dblclick()
    page1.get_by_test_id("dialog-defaultFooter-confirm-button").click()
    page1.get_by_role("button", name="New").click()
    page1.get_by_role("textbox", name="workout name, like Day 1 Abs").fill("Chest Day")
    page1.get_by_test_id("workoutBuilder-startBuildingButton").click()
    page1.get_by_role("textbox", name="Search for an exercise").click()
    page1.get_by_role("textbox", name="Search for an exercise").fill("Bench Press")
    page1.locator("div").filter(has_text=re.compile(r"^\+ Add custom exerciseRelevance$")).nth(1).click()
    page1.get_by_role("textbox", name="Search for an exercise").click()
    page1.get_by_role("textbox", name="Search for an exercise").press("Enter")
    page1.get_by_test_id("exerciseLibrary-exercise-declineBenchPress").locator("div").first.click()
    page1.get_by_role("button", name="Add to Workout").click()
    page1.get_by_role("textbox", name="Search for an exercise").dblclick()
    page1.get_by_role("textbox", name="Search for an exercise").fill("dumbell bench press")
    page1.get_by_role("textbox", name="Search for an exercise").press("Enter")
    page1.get_by_text("No compatible source was").click()
    page1.get_by_role("button", name="Add to Workout").click()
    page1.get_by_role("textbox", name="Search for an exercise").dblclick()
    page1.get_by_role("textbox", name="Search for an exercise").fill("cable chest flys")
    page1.get_by_role("textbox", name="Search for an exercise").press("Enter")
    page1.get_by_text("No compatible source was").click()
    page1.get_by_role("button", name="Add to Workout").click()
    page1.get_by_text("No compatible source was").click()
    page1.get_by_text("This is an upper chest").click()
    page1.get_by_role("button", name="Add to Workout").click()
    page1.get_by_role("textbox", name="Search for an exercise").dblclick()
    page1.get_by_role("textbox", name="Search for an exercise").fill("tricep push down")
    page1.get_by_role("textbox", name="Search for an exercise").press("Enter")
    page1.get_by_text("No compatible source was").click()
    page1.get_by_role("button", name="Add to Workout").click()
    page1.get_by_role("button", name="Increase Value").first.click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").first.click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").first.fill("10")
    page1.get_by_role("button", name="Increase Value").nth(1).click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").nth(1).click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").nth(1).fill("10")
    page1.get_by_role("button", name="Increase Value").nth(2).click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").nth(2).click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").nth(2).fill("10")
    page1.get_by_test_id("workoutBuilder-recordTypeInput").first.click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").first.fill("6")
    page1.get_by_role("button", name="Increase Value").nth(3).click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").nth(3).click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").nth(3).fill("6")
    page1.get_by_role("button", name="Increase Value").nth(4).click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").nth(3).click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").nth(3).fill("10")
    page1.get_by_test_id("workoutBuilder-recordTypeInput").nth(4).click()
    page1.get_by_test_id("workoutBuilder-recordTypeInput").nth(4).fill("12")
    page1.get_by_test_id("workoutBuilder-saveBtn").click()
    page1.get_by_role("button", name="New").click()
    page1.get_by_role("textbox", name="workout name, like Day 1 Abs").fill("Back Day")
    page1.get_by_test_id("workoutBuilder-startBuildingButton").click()
    page1.get_by_role("textbox", name="Search for an exercise").click()
    page1.get_by_role("textbox", name="Search for an exercise").fill("Chin up")
    page1.get_by_role("textbox", name="Search for an exercise").press("Enter")
    page1.get_by_text("No compatible source was").click()
    page1.get_by_role("button", name="Add to Workout").click()
    page1.get_by_text("+ Add custom exerciseRelevance").click()
    page1.get_by_test_id("workoutBuilder-saveBtn").click()
    page1.get_by_test_id("grid-row-backDay").get_by_text("Schedule").click()
    page1.get_by_text("12", exact=True).first.click()
    page1.get_by_text("19").first.click()
    page1.get_by_text("26").first.click()
    page1.get_by_text("2", exact=True).nth(2).click()
    page1.get_by_text("9", exact=True).nth(1).click()
    page1.get_by_text("16").nth(1).click()
    page1.get_by_text("Shannon's program(12 May 2025 - 22 Jun 2025)Main programShannons Program12 May").click()
    page1.get_by_test_id("leftNavMenu-item-calendar").click()
    page1.locator("div:nth-child(3) > div > div:nth-child(3) > div").first.click(button="right")
    page1.get_by_test_id("dropdownButton-menuItem-cardio").get_by_text("Cardio").click()
    page1.get_by_text("Running").click()
    page1.get_by_text("Walking").click()
    page1.get_by_test_id("multipleActivitiesDialog-activity-cardio-target-radio-time").check()
    page1.get_by_role("textbox", name=":00:00").click()
    page1.get_by_role("button", name="01").first.click()
    page1.get_by_role("button", name="01").first.press("Enter")
    page1.get_by_role("button", name="01").first.press("Enter")
    page1.locator("div").filter(has_text=re.compile(r"^Walk for$")).first.click()
    page1.get_by_title("Tuesday").click()
    page1.get_by_test_id("weekPicker-button-m").click()
    page1.get_by_test_id("weekPicker-button-w").click()
    page1.get_by_test_id("weekPicker-button-f").click()
    page1.get_by_title("Saturday").click()
    page1.get_by_title("Thursday").click()
    page1.get_by_test_id("repeatDialog-weeklyRepeatFor-select").locator("svg").click()
    page1.get_by_test_id("repeatDialog-weeklyRepeatFor-option-52").click()
    page1.get_by_test_id("dialog-defaultFooter-confirm-button").click()
    page1.get_by_test_id("multipleActivitiesDialog-saveButton").click()
    page1.locator("label").filter(has_text="Message").click()
    page1.get_by_role("combobox").filter(has_text=re.compile(r"^$")).fill("Heya! All onboared - i keep messaging for my insta dms - any questions hit me there! Chat soon! Glad to have you onboard!")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)