#!/usr/bin/env python3
"""
Smart Coach Apply Fixed - Handles stale elements and exercise name mismatches
"""

import json
import logging
from weekly_program_updater_fixed import TrainerizeAutomation
import time

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('smart_coach_apply_fixed.log'),
        logging.StreamHandler()
    ]
)


def load_smart_progressions(filename='nicole_lynch_smart_progressions.json'):
    """Load the smart progressions generated by the simple test"""
    try:
        with open(filename, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        logging.error(f"Smart progressions file {filename} not found.")
        return None
    except Exception as e:
        logging.error(f"Error loading smart progressions: {e}")
        return None


def apply_remaining_progressions():
    """Apply the remaining progressions that failed"""

    print("=" * 60)
    print("SMART COACH - APPLY REMAINING PROGRESSIONS")
    print("=" * 60)

    # Load the smart progressions
    progressions_data = load_smart_progressions()
    if not progressions_data:
        print("❌ Failed to load smart progressions")
        return

    client_name = "Nicole Lynch"
    workouts = progressions_data[client_name]

    # Show what we need to fix
    print("🔧 REMAINING PROGRESSIONS TO APPLY:")
    print("\n  ❌ Leg Day:")
    print("    • Standing Calf Raise: GOALS: S1: 37.5kg*15 | S2: 37.5kg*15 | S3: 37.5kg*15")
    print("\n  ❌ Chest Day (all exercises):")
    for exercise in workouts['Chest Day']:
        print(f"    • {exercise['exercise_name']}: {exercise['reps']}")

    # Ask for confirmation
    response = input(f"\n🤖 Apply these remaining progressions? (y/n): ")
    if response.lower() != 'y':
        print("Operation cancelled.")
        return

    try:
        # Initialize the automation system with enhanced settings
        automation = TrainerizeAutomation()

        # Login to Trainerize
        print("\n🔐 Logging into Trainerize...")
        username = "shannonbirch@cocospersonaltraining.com"
        password = "cyywp7nyk2"

        if not automation.login(username, password):
            print("❌ Failed to login to Trainerize")
            return

        print("✅ Successfully logged into Trainerize!")

        # Navigate to Nicole Lynch
        print(f"\n🚀 Navigating to {client_name}...")
        if not automation.navigate_to_client(client_name):
            print(f"❌ Failed to navigate to {client_name}")
            return

        print("✅ Successfully navigated to client!")

        # Navigate to Training Program tab
        if not automation.navigate_to_training_program():
            print("❌ Failed to navigate to Training Program tab")
            return

        print("✅ Successfully navigated to Training Program!")

        # Apply remaining progressions
        results = {"successful": [], "failed": []}

        # 1. Fix Standing Calf Raise in Leg Day
        print("\n🦵 Fixing Standing Calf Raise in Leg Day...")
        try:
            if automation.click_workout("Leg Day"):
                if automation.edit_workout():
                    # Try to update Standing Calf Raise with retry logic
                    exercise_name = "Standing Calf Raise"
                    goals = "GOALS: S1: 37.5kg*15 | S2: 37.5kg*15 | S3: 37.5kg*15"

                    # Try multiple times with fresh element lookups
                    success = False
                    for attempt in range(3):
                        try:
                            print(
                                f"  Attempt {attempt + 1} to update {exercise_name}...")
                            time.sleep(2)  # Wait for page stability

                            if automation.update_exercise_goal(exercise_name, goals):
                                print(
                                    f"  ✅ Successfully updated {exercise_name}!")
                                results["successful"].append(
                                    f"Leg Day - {exercise_name}")
                                success = True
                                break
                            else:
                                print(f"  ❌ Attempt {attempt + 1} failed")
                        except Exception as e:
                            print(
                                f"  ❌ Attempt {attempt + 1} error: {str(e)[:100]}...")
                            time.sleep(3)

                    if not success:
                        results["failed"].append(f"Leg Day - {exercise_name}")

                    # Save workout
                    automation.save_workout()
                    automation.navigate_back_to_program()
        except Exception as e:
            print(f"❌ Error with Leg Day: {e}")
            results["failed"].append("Leg Day - Standing Calf Raise")

        # 2. Fix Chest Day exercises with name matching
        print("\n💪 Fixing Chest Day exercises...")
        try:
            if automation.click_workout("Chest Day"):
                if automation.edit_workout():

                    # Map exercise names to likely Trainerize names
                    exercise_mappings = {
                        "Barbell Bench": ["Barbell Bench Press", "Bench Press", "Barbell Chest Press"],
                        "Dumbbell Chest Press": ["Dumbbell Bench Press", "DB Chest Press", "Chest Press"],
                        "Cable Chest Dip": ["Cable Dip", "Chest Dip", "Cable Chest Dips"],
                        "Rope Tricep Pushdown": ["Tricep Pushdown", "Cable Tricep Pushdown", "Rope Pushdown"]
                    }

                    for original_name, exercise_data in zip(
                        ["Barbell Bench", "Dumbbell Chest Press",
                            "Cable Chest Dip", "Rope Tricep Pushdown"],
                        workouts['Chest Day']
                    ):
                        possible_names = exercise_mappings.get(
                            original_name, [original_name])
                        goals = exercise_data['reps']

                        success = False
                        for possible_name in possible_names:
                            try:
                                print(
                                    f"  Trying to update '{possible_name}' with {goals}...")
                                time.sleep(2)

                                if automation.update_exercise_goal(possible_name, goals):
                                    print(
                                        f"  ✅ Successfully updated {possible_name}!")
                                    results["successful"].append(
                                        f"Chest Day - {possible_name}")
                                    success = True
                                    break
                                else:
                                    print(
                                        f"  ❌ Failed to find/update {possible_name}")
                            except Exception as e:
                                print(
                                    f"  ❌ Error with {possible_name}: {str(e)[:50]}...")

                        if not success:
                            results["failed"].append(
                                f"Chest Day - {original_name}")

                    # Save workout
                    automation.save_workout()
                    automation.navigate_back_to_program()
        except Exception as e:
            print(f"❌ Error with Chest Day: {e}")
            results["failed"].extend(
                [f"Chest Day - {ex['exercise_name']}" for ex in workouts['Chest Day']])

        # Show final results
        print(f"\n{'='*60}")
        print("SMART COACH FIXED APPLICATION RESULTS")
        print(f"{'='*60}")

        if results["successful"]:
            print(f"\n✅ SUCCESSFULLY UPDATED ({len(results['successful'])}):")
            for item in results["successful"]:
                print(f"  • {item}")

        if results["failed"]:
            print(f"\n❌ STILL FAILED ({len(results['failed'])}):")
            for item in results["failed"]:
                print(f"  • {item}")

        total_attempted = len(results["successful"]) + len(results["failed"])
        success_rate = (
            len(results["successful"]) / total_attempted * 100) if total_attempted > 0 else 0

        print(f"\n📊 FINAL STATS:")
        print(
            f"  Success Rate: {success_rate:.1f}% ({len(results['successful'])}/{total_attempted})")

        if len(results["successful"]) > 0:
            print(f"\n🎯 Nicole Lynch's workouts have been further updated!")
            print(f"   Combined with previous success: Back Day (5/5) + new fixes")

    except Exception as e:
        logging.error(f"Error applying remaining progressions: {e}")
        print(f"❌ Error: {e}")

    finally:
        # Cleanup
        try:
            automation.cleanup()
        except:
            pass


def main():
    """Main function"""
    apply_remaining_progressions()


if __name__ == "__main__":
    main()
