#!/usr/bin/env python3
"""
Smart Coach Apply to Trainerize - Final Complete System
Applies smart progressions generated by smart_coach_simple_test.py to Trainerize
"""

import json
import logging
from weekly_program_updater_fixed import TrainerizeAutomation

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('smart_coach_apply_to_trainerize.log'),
        logging.StreamHandler()
    ]
)


def load_smart_progressions(filename='nicole_lynch_smart_progressions.json'):
    """Load the smart progressions generated by the simple test"""
    try:
        with open(filename, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        logging.error(
            f"Smart progressions file {filename} not found. Run smart_coach_simple_test.py first.")
        return None
    except Exception as e:
        logging.error(f"Error loading smart progressions: {e}")
        return None


def apply_smart_progressions_to_trainerize():
    """Apply smart progressions to Trainerize using the weekly program updater"""

    print("=" * 60)
    print("SMART COACH - APPLY TO TRAINERIZE")
    print("=" * 60)
    print("This system will apply the smart progressions to Nicole Lynch's workouts in Trainerize")

    # Load the smart progressions
    progressions_data = load_smart_progressions()
    if not progressions_data:
        print("❌ Failed to load smart progressions")
        return

    # Show summary
    client_name = "Nicole Lynch"
    workouts = progressions_data[client_name]
    total_exercises = sum(len(exercises) for exercises in workouts.values())

    print(f"\n📋 Smart Progressions Summary:")
    print(f"   Client: {client_name}")
    print(f"   Workouts: {len(workouts)} ({', '.join(workouts.keys())})")
    print(f"   Total exercises: {total_exercises}")

    # Show detailed breakdown
    for workout_name, exercises in workouts.items():
        print(f"\n  🏋️ {workout_name}: {len(exercises)} exercises")
        for exercise in exercises:
            print(f"    • {exercise['exercise_name']}: {exercise['reps']}")

    # Ask for confirmation
    response = input(
        f"\n🤖 Apply these smart progressions to {client_name} in Trainerize? (y/n): ")
    if response.lower() != 'y':
        print("Operation cancelled.")
        return

    try:
        # Initialize the automation system
        automation = TrainerizeAutomation()

        # Login to Trainerize
        print("\n🔐 Logging into Trainerize...")
        username = "shannonbirch@cocospersonaltraining.com"
        password = "cyywp7nyk2"

        if not automation.login(username, password):
            print("❌ Failed to login to Trainerize")
            return

        print("✅ Successfully logged into Trainerize!")

        # Apply progressions using the process_multiple_clients method
        print(f"\n🚀 Applying smart progressions to {client_name}...")

        # Convert the data format for the weekly program updater
        # It expects: {client_name: {workout_name: [exercise_data_list]}}
        formatted_data = {client_name: workouts}

        # Process the client
        results = automation.process_multiple_clients(formatted_data)

        # Show results
        print(f"\n{'='*60}")
        print("SMART COACH APPLICATION RESULTS")
        print(f"{'='*60}")

        if client_name in results:
            result = results[client_name]
            if result.get('status') == 'success':
                print(
                    f"✅ Successfully applied smart progressions to {client_name}!")
                print(f"   All workouts updated with intelligent rep progressions")
                print(
                    f"   Nicole's program now follows the 6→8→10→12→15→weight increase algorithm")
            else:
                print(f"❌ Failed to apply progressions to {client_name}")
                print(f"   Error: {result.get('error', 'Unknown error')}")
        else:
            print(f"❌ No results found for {client_name}")

        print(f"\n🎯 Smart Coach System Complete!")
        print(f"   Nicole Lynch's workouts have been intelligently updated")
        print(f"   Each exercise progressed based on real performance data")
        print(f"   Next week: Nicole will follow the new progressive goals")

    except Exception as e:
        logging.error(f"Error applying smart progressions: {e}")
        print(f"❌ Error: {e}")

    finally:
        # Cleanup
        try:
            automation.cleanup()
        except:
            pass


def main():
    """Main function"""
    apply_smart_progressions_to_trainerize()


if __name__ == "__main__":
    main()
