from flask import Flask, request, jsonify
import google.generativeai as genai
import os
import re

app = Flask(__name__)

gemini_api_key = None


def setup_gemini(api_key):
    global gemini_api_key
    gemini_api_key = api_key
    genai.configure(api_key=gemini_api_key)


@app.route('/adjust-code', methods=['POST'])
def adjust_code():
    data = request.get_json()
    if not data or 'output' not in data:
        return jsonify({'error': 'No output provided'}), 400

    output = data['output']
    # Use a regular expression to extract the generated comments
    comment_pattern = r"✔️ Gemini Generated Comment: (.*?)(?=(?:✔️ Gemini Generated Comment:|\n==================================================|$))"
    matches = re.findall(comment_pattern, output, re.DOTALL)
    generated_comments = [match.strip() for match in matches]

    if not generated_comments:
        prompt = f"""
       You are an AI coding assistant. Your goal is to help debug a python script, specifically the functionality around generating Instagram comments.
       The bot does not appear to be generating any comments. Please tell me why this might be the case.

       Here is the output of the script after it was run:
        {output}
      
      """
    else:
        prompt = f"""
        You are an AI coding assistant. Your goal is to help debug a python script, specifically the functionality around generating Instagram comments.

       Here are some of the example comments that were generated by a bot:
        
       {generated_comments}
       
        Here is the output of the script after it was run:
        
        {output}

         Please provide me with some example comments that I should use in my bot.
         These comments should be specific to an Instagram post, and the format of the output should be single line, with no option numbers.
       """

    try:
        model = genai.GenerativeModel('gemini-pro')
        response = model.generate_content(prompt)
        adjusted_code = response.text
        return jsonify({'adjusted_code': adjusted_code})
    except Exception as e:
        return jsonify({'error': f"Error processing with Gemini: {str(e)}"}), 500


if __name__ == '__main__':
    setup_gemini("AIzaSyA3bMRGd2KfTrf_G6YuUIDiq7F94w1EDFw")
    app.run(debug=False, port=5001, use_reloader=False)  # Changed to False
